import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Poppins } from "@next/font/google"
import "./globals.css";
import Top_Header from '@/app/components/header/top_header'
import Navbar from '@/app/components/header/navbar'
import Footer from '@/app/components/footer/footer'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // Choose your weights
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Top_Header/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
